GET http://localhost:8080/login?username=tom&password=123456

###
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded
username=tom&password=123456
###
GET http://localhost:8080/getuser
###
GET http://localhost:8080/getUserById?id=1
###
POST http://localhost:8080/insert
Content-Type: application/json

{
  "username":"xl",
  "password":"123456",
  "nickname":"小亮"
}
###
PUT http://localhost:8080/update
Content-Type: application/json

{
  "id": "3",
  "nickname": "man"
}
###
DELETE http://localhost:8080/delete?id=3
